name: Algolia Automations

on:
  push:
    branches:
      - master

jobs:
  sync_synonyms_job:
    runs-on: ubuntu-latest
    name: Sync synonym list with Algolia indexes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: |
          echo "result=$(git diff --name-only HEAD^ HEAD ./config/algolia-synonyms.yml)" >> "$GITHUB_OUTPUT"
        id: synonyms_changed
      - run: yarn sync-synonyms
        if: steps.synonyms_changed.outputs.result == 'config/algolia-synonyms.yml'
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
