name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: volta-cli/action@efb293bee52c8749b10ecda410b3a3c441fe94d8 # v1
        with:
          cache: yarn
          node-version: '14'
      - name: Install Depdendencies
        run: |
          yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
