name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          cache: yarn
          node-version: '14'
      - name: Install Depdendencies
        run: |
          yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
